// <auto-generated />
// This file was generated using Add Scaffolded Item
using Microsoft.AspNetCore.Hosting;

[assembly: HostingStartup(typeof(NeoTemplate.IdentityServer.Areas.Identity.IdentityHostingStartup))]
namespace NeoTemplate.IdentityServer.Areas.Identity
{
  /// <summary>
  /// Startup class for the identity host
  /// </summary>
  public class IdentityHostingStartup : IHostingStartup
  {
    /// <inheritdoc/>
    public void Configure(IWebHostBuilder builder)
    {
      builder.ConfigureServices((context, services) =>
      {
      });
    }
  }
}