// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tuckshop.Core.Models;

#nullable disable

namespace Tuckshop.Core.Models.Migrations.Migrations
{
    [DbContext(typeof(ModelDbContext))]
    [Migration("20241113071049_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Neo.OneTimeTokens.OneTimeToken", b =>
                {
                    b.Property<string>("Token")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("Expiry")
                        .HasColumnType("datetime");

                    b.Property<string>("Info")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Token");

                    b.ToTable("OneTimeTokens");
                });

            modelBuilder.Entity("Tuckshop.Core.Models.Files.FileDescriptor", b =>
                {
                    b.Property<int>("FileDescriptorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FileDescriptorId"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("FileDataId")
                        .HasColumnType("int");

                    b.Property<byte[]>("FileHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varbinary(32)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("FileDescriptorId");

                    b.ToTable("FileDescriptors");
                });

            modelBuilder.Entity("Tuckshop.Core.Models.Identity.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("IdentityGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("UserId");

                    b.HasIndex("IdentityGuid", "ClientId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Tuckshop.Core.Models.Files.FileDescriptor", b =>
                {
                    b.OwnsOne("Neo.Model.ValueObjects.AuditValues", "Audit", b1 =>
                        {
                            b1.Property<int>("FileDescriptorId")
                                .HasColumnType("int");

                            b1.Property<int>("CreatedBy")
                                .HasColumnType("int");

                            b1.Property<DateTime>("CreatedOn")
                                .HasColumnType("datetime");

                            b1.Property<int>("ModifiedBy")
                                .HasColumnType("int");

                            b1.Property<DateTime>("ModifiedOn")
                                .HasColumnType("datetime");

                            b1.HasKey("FileDescriptorId");

                            b1.ToTable("FileDescriptors");

                            b1.WithOwner()
                                .HasForeignKey("FileDescriptorId");
                        });

                    b.Navigation("Audit");
                });
#pragma warning restore 612, 618
        }
    }
}
