// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NeoTemplate;

namespace NeoTemplate.Models.Migrations.Migrations
{
    [DbContext(typeof(ReportingDbContext))]
    [Migration("20210606182719_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Neo.OneTimeTokens.OneTimeToken", b =>
                {
                    b.Property<string>("Token")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("Expiry")
                        .HasColumnType("datetime");

                    b.Property<string>("Info")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Token");

                    b.ToTable("OneTimeTokens");
                });

            modelBuilder.Entity("Neo.Reporting.Models.ReportDataEntry", b =>
                {
                    b.Property<int>("ReportDataEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ReportData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReportRequestId")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ValidUntil")
                        .HasColumnType("datetime");

                    b.HasKey("ReportDataEntryId");

                    b.HasIndex("ReportRequestId")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.ToTable("ReportDataEntries");
                });

            modelBuilder.Entity("Neo.Reporting.Models.ReportRequest", b =>
                {
                    b.Property<int>("ReportRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Criteria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataLoadCompletedOn")
                        .HasColumnType("datetime");

                    b.Property<int?>("DataLoadReportRequestId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataLoadStartedOn")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DataRequestedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Error")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("ReportKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RequestType")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<string>("RequestedByUserGuid")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("ReportRequestId");

                    b.HasIndex("RequestType");

                    b.HasIndex("Status");

                    b.HasIndex("TenantId");

                    b.ToTable("ReportRequests");
                });

            modelBuilder.Entity("Neo.Reporting.Models.ReportRequestStatusHistory", b =>
                {
                    b.Property<int>("ReportRequestStatusHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<int>("ReportRequestId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ReportRequestStatusHistoryId");

                    b.HasIndex("ReportRequestId");

                    b.HasIndex("Status");

                    b.ToTable("ReportRequestStatusHistory");
                });

            modelBuilder.Entity("ReportRequestStatusEntity", b =>
                {
                    b.Property<int>("ReportRequestStatusId")
                        .HasColumnType("int");

                    b.Property<string>("ReportRequestStatusName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ReportRequestStatusId");

                    b.ToTable("ReportRequestStatuses");

                    b.HasData(
                        new
                        {
                            ReportRequestStatusId = 1,
                            ReportRequestStatusName = "Created"
                        },
                        new
                        {
                            ReportRequestStatusId = 2,
                            ReportRequestStatusName = "Request For Data Created"
                        },
                        new
                        {
                            ReportRequestStatusId = 10,
                            ReportRequestStatusName = "Loading Data"
                        },
                        new
                        {
                            ReportRequestStatusId = 11,
                            ReportRequestStatusName = "Loading Data Completed"
                        },
                        new
                        {
                            ReportRequestStatusId = 20,
                            ReportRequestStatusName = "Data Requested"
                        },
                        new
                        {
                            ReportRequestStatusId = 30,
                            ReportRequestStatusName = "Data No Longer Available"
                        },
                        new
                        {
                            ReportRequestStatusId = 31,
                            ReportRequestStatusName = "Data Removed"
                        },
                        new
                        {
                            ReportRequestStatusId = 32,
                            ReportRequestStatusName = "Data Expired"
                        },
                        new
                        {
                            ReportRequestStatusId = -1,
                            ReportRequestStatusName = "Build Report Failed"
                        },
                        new
                        {
                            ReportRequestStatusId = -2,
                            ReportRequestStatusName = "Loading Data Failed"
                        },
                        new
                        {
                            ReportRequestStatusId = -3,
                            ReportRequestStatusName = "Report Ready Event Failed"
                        });
                });

            modelBuilder.Entity("ReportRequestTypeEntity", b =>
                {
                    b.Property<int>("ReportRequestTypeId")
                        .HasColumnType("int");

                    b.Property<string>("ReportRequestTypeName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ReportRequestTypeId");

                    b.ToTable("ReportRequestTypes");

                    b.HasData(
                        new
                        {
                            ReportRequestTypeId = -1,
                            ReportRequestTypeName = "View Denied"
                        },
                        new
                        {
                            ReportRequestTypeId = 1,
                            ReportRequestTypeName = "View"
                        },
                        new
                        {
                            ReportRequestTypeId = 2,
                            ReportRequestTypeName = "View Data"
                        },
                        new
                        {
                            ReportRequestTypeId = 3,
                            ReportRequestTypeName = "Load Data"
                        },
                        new
                        {
                            ReportRequestTypeId = 101,
                            ReportRequestTypeName = "Download Pdf"
                        },
                        new
                        {
                            ReportRequestTypeId = 102,
                            ReportRequestTypeName = "Download Excel"
                        });
                });

            modelBuilder.Entity("NeoTemplate.Models.Identity.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("IdentityGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Neo.Reporting.Models.ReportRequest", b =>
                {
                    b.HasOne("ReportRequestTypeEntity", null)
                        .WithMany()
                        .HasForeignKey("RequestType")
                        .HasConstraintName("ReportRequest_ReportRequestType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReportRequestStatusEntity", null)
                        .WithMany()
                        .HasForeignKey("Status")
                        .HasConstraintName("ReportRequest_ReportRequestStatus")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Neo.Reporting.Models.ReportRequestStatusHistory", b =>
                {
                    b.HasOne("Neo.Reporting.Models.ReportRequest", "ReportRequest")
                        .WithMany("StatusHistory")
                        .HasForeignKey("ReportRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReportRequestStatusEntity", null)
                        .WithMany()
                        .HasForeignKey("Status")
                        .HasConstraintName("ReportRequestStatusHistory_ReportRequestStatus")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReportRequest");
                });

            modelBuilder.Entity("Neo.Reporting.Models.ReportRequest", b =>
                {
                    b.Navigation("StatusHistory");
                });
        }
    }
}
