# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json

name: "Copilot Setup Steps"

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest

    permissions:
      packages: read

    steps:
      - name: Add Singular GitHub NuGet source
        run: dotnet nuget add source --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name "Singular GitHub" "https://nuget.pkg.github.com/SingularSystems/index.json"