<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>14.0</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Company>Singular Systems (Pty) Ltd</Company>
    <Authors>$(Company)</Authors>
    <Copyright>$([System.DateTime]::Now.ToString(yyyy)) by $(Company)</Copyright>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <RunAnalyzersDuringLiveAnalysis>true</RunAnalyzersDuringLiveAnalysis>
    <RunAnalyzersDuringBuild>true</RunAnalyzersDuringBuild>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisLevel>latest</AnalysisLevel>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="IronPdf" />
    <PackageReference Include="Neo.Model.App" />
    <PackageReference Include="Neo.Model.Swagger" />
    <PackageReference Include="Neo.Reporting.Api" />
    <PackageReference Include="Neo.Reporting.IronPdf2022" />
    <PackageReference Include="Neo.Reporting.Notifications" />
    <PackageReference Include="Neo.Reporting.PdfSharp" />
  </ItemGroup>

  <ItemGroup Condition="$([MSBuild]::IsOsPlatform('Linux'))">
    <PackageReference Include="IronPdf.Native.Chrome.Linux" />
    <PackageReference Include="IronSoftware.Native.PdfModel.Linux" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NeoTemplate.RazorReports\NeoTemplate.RazorReports.csproj" />
    <ProjectReference Include="..\NeoTemplate.Reporting.Migrations\NeoTemplate.Reporting.Migrations.csproj" />
  </ItemGroup>

</Project>